In [575]:
import numpy as np
from numpy import linalg as la
import matplotlib as mat

In [576]:
#array_type = np.dtype([('f0', 'U12'), ('f1', 'U3'), ('f2', 'U2'), ('f3', '<f8'), ('f4', 'U9')])

#np.genfromtxt(csv_file, dtype=None, delimiter=',',usecols=(0,1,2,4))

data1 = np.genfromtxt('airbnbdata1.csv', delimiter=",", dtype='U20', usecols=(0,2,3,4,5)) # got weird error when extract column 1
data1_name = data1[0,:]
data1 = data1[1:,:];
data2 = np.genfromtxt('airbnbdata1.csv', delimiter=",", dtype='U40', usecols=(6, 7, 8, 9, 10, 11,12,13,14,15,16,17,18,19,20,21,22, 23, 24))
data2_name = data2[0,:]; # Extract the heading
data2 = np.genfromtxt('airbnbdata1.csv', delimiter=",", dtype='float', usecols=(6, 7, 8, 9, 10, 11,12,13,14,15,16,17,18,19,20,21,22, 23, 24))
data2 = data2[1:,:];

m = data1.shape[0] # number of samples
print('data1 shape is')
print(data1.shape)
print()
print('data2 shape is')
print(data2.shape)
print()
data_name = []
for i in range(len(data1_name)):
    data_name.append(data1_name[i])

for i in range(len(data2_name)):
    data_name.append(data2_name[i])

print('data name is')
print(data_name)

data1 shape is
(5098, 5)

data2 shape is
(5098, 19)

data name is
['host_response_time', 'property_type', 'room_type', 'bed_type', 'cancellation_policy', 'zipcode', 'host_acceptance_rate', 'price', 'security_deposit', 'cleaning_fee', 'extra_people', 'reviews_per_month', 'host_response_rate', 'accommodates', 'bathrooms', 'bedrooms', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'number_of_reviews', 'review_scores_rating', 'require_guest_profile_picture', 'require_guest_phone_verification']


In [577]:
print(data2[17])

[  9.41170000e+04   7.60000000e-01   1.49000000e+02   0.00000000e+00
   1.00000000e+02   0.00000000e+00   6.50000000e-01   1.00000000e+00
   2.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+01
   1.50000000e+01   3.90000000e+01   3.14000000e+02   6.00000000e+00
   1.00000000e+02   0.00000000e+00   0.00000000e+00]


In [578]:
###### data processing to categorize

host_res = np.zeros([m,1])
prop = np.zeros([m,1])
room_type = np.zeros([m,1])
bed_type = np.zeros([m,1])
cancel = np.zeros([m,1])
for i in range(m):
    for j in range(6):
        if j==0:
            # a few days or more = 0
            # within a day = 1
            # within a few hours = 2
            #  within an hour = 3
            if data1[i,j] == 'a few days or more':
                host_res[i,0] = 0;
            elif data1[i,j] == 'within a day':
                host_res[i,0] = 1;
            elif data1[i,j] == 'within a few hours':
                host_res[i,0] = 2;
            elif data1[i,j] == 'within an hour':
                host_res[i,0] = 3;
        if j==1:
            #Apartment = 0
            #Cabin = 1
            #Condominium = 2 
            #House = 3
            if data1[i,j] == 'Apartment':
                prop[i,0] = 0;
            elif data1[i,j] == 'Cabin':
                prop[i,0] = 1;
            elif data1[i,j] == 'Condominium':
                prop[i,0] = 2;
            elif data1[i,j] == 'House':
                prop[i,0] = 3;
        if j==2:
            #Entire home/apt = 0
            #Private room = 1
            #Shared room = 2
            if data1[i,j] == 'Entire home/apt':
                room_type[i,0] = 0;
            elif data1[i,j] == 'Private room':
                room_type[i,0] = 1;
            elif data1[i,j] == 'Shared room':
                room_type[i,0] = 2;
        if j==3:
            #Airbed = 0
            #Couch = 1
            #Futon  = 2
            #Pull-out Sofa = 3 
            #Real Bed = 4
            if data1[i,j] == 'Airbed':
                bed_type[i,0] = 0;
            elif data1[i,j] == 'Couch':
                bed_type[i,0] = 1;
            elif data1[i,j] == 'Futon':
                bed_type[i,0] = 2;
            elif data1[i,j] == 'Pull-out Sofa':
                bed_type[i,0] = 3; 
            elif data1[i,j] == 'Real Bed':
                bed_type[i,0] = 4;
        if j==4:
            #flexible = 0
            #moderate = 1
            #strict = 2
            if data1[i,j] == 'flexible':
                cancel[i,0] = 0;
            elif data1[i,j] == 'moderate':
                cancel[i,0] = 1;
            elif data1[i,j] == 'strict':
                cancel[i,0] = 2;

print(data1[4,4])
print(cancel[4,0])
print()

flexible
0.0



In [579]:
data1

array([['within an hour', 'Condominium', 'Entire home/apt', 'Real Bed',
        'strict'],
       ['within an hour', 'House', 'Private room', 'Futon', 'strict'],
       ['within an hour', 'Apartment', 'Entire home/apt', 'Real Bed',
        'strict'],
       ..., 
       ['within an hour', 'House', 'Shared room', 'Real Bed', 'moderate'],
       ['within an hour', 'House', 'Shared room', 'Real Bed', 'moderate'],
       ['within an hour', 'House', 'Shared room', 'Real Bed', 'moderate']], 
      dtype='<U20')

In [580]:
p_data =  np.column_stack((host_res, prop, room_type, bed_type, cancel))
print(p_data.shape)
print(p_data)

(5098, 5)
[[ 3.  2.  0.  4.  2.]
 [ 3.  3.  1.  2.  2.]
 [ 3.  0.  0.  4.  2.]
 ..., 
 [ 3.  3.  2.  4.  1.]
 [ 3.  3.  2.  4.  1.]
 [ 3.  3.  2.  4.  1.]]


In [581]:
data2[0,18]

0.0

In [582]:
np.savetxt('categorized_data.csv', p_data, delimiter=',')   # X is an array

In [583]:
np.savetxt('data2.csv', data2, delimiter=',')   # X is an array

In [584]:
data2[17]

array([  9.41170000e+04,   7.60000000e-01,   1.49000000e+02,
         0.00000000e+00,   1.00000000e+02,   0.00000000e+00,
         6.50000000e-01,   1.00000000e+00,   2.00000000e+00,
         1.00000000e+00,   1.00000000e+00,   1.00000000e+01,
         1.50000000e+01,   3.90000000e+01,   3.14000000e+02,
         6.00000000e+00,   1.00000000e+02,   0.00000000e+00,
         0.00000000e+00])